// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"server2/cmd/handler"
	"server2/internal/storages"
	"server2/internal/token"
)

import (
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func initHandler() *handler.Handler {
	controller := token.NewController()
	service := storages.NewService()
	storagesController := storages.NewController(service)
	handlerHandler := handler.NewHandler(controller, storagesController)
	return handlerHandler
}

// wire.go:

var serviceSet = wire.NewSet(storages.NewService)

var controllerSet = wire.NewSet(token.NewController, storages.NewController)

var handlerSet = wire.NewSet(handler.NewHandler)

var appSet = wire.NewSet(
	serviceSet,
	controllerSet,
	handlerSet,
)
